describe('dap.ext.vscode', function()
  it('can load launch.json file and map adapter type to filetypes', function()
    local dap = require('dap')
    local vscode = require('dap.ext.vscode')
    vscode.load_launchjs('tests/launch.json', { bar = {'c', 'cpp'} })
    assert.are.same(3, vim.tbl_count(dap.configurations))
    assert.are.same({{ type = 'java', request = 'launch' },}, dap.configurations.java)
    assert.are.same({{ type = 'bar', request = 'attach' },}, dap.configurations.c)
    assert.are.same({{ type = 'bar', request = 'attach' },}, dap.configurations.cpp)
  end)
end)
