name: "release"
on:
  push:
    tags:
      - '*'
jobs:
  luarocks-upload:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v2.0.0
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          detailed_description: |
            nvim-dap allows you to:

            * Launch an application to debug
            * Attach to running applications and debug them
            * Set breakpoints and step through code
            * Inspect the state of the application
          copy_directories:
            doc
            plugin
